queue:
  name: DCT
  demands: 
  - IsBuildServer
  - msbuild
  - vstest

#Your build pipeline references the ‘BuildPlatform’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
steps:
- task: gittools.gitversion.gitversion-task.GitVersion@4
  displayName: GitVersion
  inputs:
    updateAssemblyInfo: true

    preferBundledVersion: false


- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.0.8'
  inputs:
    version: 2.0.8

  enabled: false

- task: VisualStudioTestPlatformInstaller@1
  displayName: 'Visual Studio Test Platform Installer'
  inputs:
    versionSelector: latestStable

  enabled: false

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet <4.8.0'
  inputs:
    versionSpec: '<4.8.0'

    checkLatest: true


- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    vstsFeed: '1d5deb2d-cf8b-4bb1-b147-d13bc246e3f4'


- task: DeleteFiles@1
  displayName: 'Delete appsettings.Development.json'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'

    Contents: |
     **/appsettings.Development.json
     


- task: MSBuild@1
  displayName: 'Build solution **/*.sln'
  inputs:
    msbuildArchitecture: x64

    platform: '$(BuildPlatform)'

    configuration: '$(BuildConfiguration)'

    msbuildArguments: ' -p:version=$(Build.BuildNumber) -p:FileVersion=$(Build.BuildNumber)'

    clean: true

    maximumCpuCount: true

    restoreNugetPackages: true

    logProjectEvents: true

    createLogFile: true


- task: VSTest@2
  displayName: 'Run xUnit Tests'
  inputs:
    testAssemblyVer2: |
     **\*test*.dll
     !**\*TestAdapter.dll
     !**\*AcceptanceTests.dll
     !**\obj\**


- task: CopyFiles@2
  displayName: 'Copy Files to: Acceptance Tests to Artifact Folder'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/src/'

    Contents: '**\*AcceptanceTests*\bin\$(BuildConfiguration)\*.*'

    TargetFolder: '$(build.artifactstagingdirectory)\AcceptanceTests'

    CleanTargetFolder: true

    flattenFolders: true


- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish

    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

    vstsFeed: '1d5deb2d-cf8b-4bb1-b147-d13bc246e3f4'


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'

